### ISSUE TITLE
模块B单独编译运行，全局路由失效

### ISSUE THREAD

**Issue by hanchanpo13** [wutongke/ModularizationApp#2]
单独运行项目B，条目点击失效，debug后发现是全局路由失效
```
mRecyclerView.addOnItemTouchListener(new RecyclerItemClickListener(this, new RecyclerItemClickListener.OnItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {
//                Intent intent = new Intent(NewsListActivity.this, NewsDetailActivity.class);
//                intent.putExtra(NewsDetailActivity.NEWS, mAdapter.getItem(position));
//                startActivity(intent);
                Story story = mAdapter.getItem(position);
                boolean open = Routers.open(NewsListActivity.this, "modularization://news_detail/" + story.getId() + "/" + Utils.encodeUrlParam(story.getTitle()));
                if (open){//  <------- false
                    
                }
            }
        }));
```

**Comment by wutongke** [comment]
已经修复了，可以参考https://github.com/wutongke/ModularizationApp/commit/e050af7c91fe88f4701f5f40670086a0e1eb8b1d

**Comment by wutongke** [comment]
已经修复了，可以参考https://github.com/wutongke/ModularizationApp/commit/e050af7c91fe88f4701f5f40670086a0e1eb8b1d，感谢！

**Comment by wutongke** [comment]
已经解决了，可以参考，https://github.com/wutongke/ModularizationApp/commit/e050af7c91fe88f4701f5f40670086a0e1eb8b1d   ，感谢

**Comment by hanchanpo13** [comment]
hi，你好：


可以提供下apt源码学习吗？我想明白实现的整体思路。看过你的博客，还是有点蒙。


原始邮件
发件人:梧桐notifications@github.com
收件人:wutongke/ModularizationAppModularizationApp@noreply.github.com
抄送:Jevenhanchanpo@163.com; Authorauthor@noreply.github.com
发送时间:2017年3月14日(周二) 15:56
主题:Re: [wutongke/ModularizationApp] 模块B单独编译运行，全局路由失效 (#2)


已经解决了，可以参考，e050af7 ，感谢

**Comment by wutongke** [comment]
其实没有必要学习apt的源码，我们的路由框架用是https://github.com/mzule/ActivityRouter 我之前写过一个分析的文章 http://www.jianshu.com/p/22412a916e81 ，可以看一下思路。

现在Android也不推荐使用apt了，刚我已经把apt改为了推荐的annotationProcessor。apt的作者也已经不再维护了。

**Comment by hanchanpo13** [comment]
好的，谢谢大牛指点。


原始邮件
发件人:梧桐notifications@github.com
收件人:wutongke/ModularizationAppModularizationApp@noreply.github.com
抄送:Jevenhanchanpo@163.com; Authorauthor@noreply.github.com
发送时间:2017年3月14日(周二) 16:29
主题:Re: [wutongke/ModularizationApp] 模块B单独编译运行，全局路由失效 (#2)


其实没有必要学习apt的源码，我们的路由框架用是https://github.com/mzule/ActivityRouter 我之前写过一个分析的文章 http://www.jianshu.com/p/22412a916e81 ，可以看一下思路。
现在Android也不推荐使用apt了，刚我已经把apt改为了推荐的annotationProcessor。apt的作者也已经不再维护了。

**Comment by xingag** [comment]
博客中提到的，用annotationProcessor替代apt方式，关于多module问题，是否解决了？
